#!/bin/bash

mv src/dosbox bin/
cp src/dosbox.png bin/

cp bin/dosbox ipkg/home/retrofw/emus/dosbox/dosbox.dge
cd ipkg

tar -czvf control.tar.gz control
tar -czvf data.tar.gz home
ar rv dosbox.ipk control.tar.gz data.tar.gz debian-binary

cd ..

mv ipkg/dosbox.ipk bin/
rm ipkg/control.tar.gz
rm ipkg/data.tar.gz
rm ipkg/home/retrofw/emus/dosbox/dosbox.dge
